INSERT OR IGNORE INTO textos (id, chave, valor, nota, grupo, actualizado_em) VALUES ('acd3527b-4287-4d0e-94b7-f8ab25f407d5', 'molduras.descricao', '{"pt":"Molduras à medida com a MOLDARTPÓVOA: vidro museu Tru-Vue®, madeiras naturais e alumínio de precisão, com recolha, entrega e instalação.","en":"Bespoke framing with MOLDARTPÓVOA: Tru-Vue® museum glass, natural woods and precision aluminium, with collection, delivery and installation.","es":"Marcos a medida con MOLDARTPÓVOA: vidrio museo Tru-Vue®, maderas naturales y aluminio de precisión, con recogida, entrega e instalación."}', 'Descrição da página nos motores de busca e nos cartões de partilha.', 'molduras', 1790241005);
--> statement-breakpoint
INSERT OR IGNORE INTO textos (id, chave, valor, nota, grupo, actualizado_em) VALUES ('935102e4-a68e-417c-9f76-eb89d0510ab3', 'molduras.imagem.alt', '{"pt":"Moldura produzida em parceria com a MOLDARTPÓVOA","en":"Frame made in partnership with MOLDARTPÓVOA","es":"Marco producido en alianza con MOLDARTPÓVOA"}', 'Alternativa da fotografia, para quem não a vê. Descrever o que lá está.', 'molduras', 1790241005);
--> statement-breakpoint
INSERT OR IGNORE INTO textos (id, chave, valor, nota, grupo, actualizado_em) VALUES ('00a9b2b5-8cd9-422d-b1a7-8c334071f72a', 'molduras.imagem.legenda', '{"pt":"Molduras MOLDARTPÓVOA","en":null,"es":null}', 'Texto do marcador enquanto não houver fotografia carregada.', 'molduras', 1790241005);
--> statement-breakpoint
INSERT OR IGNORE INTO textos (id, chave, valor, nota, grupo, actualizado_em) VALUES ('16338cd2-835e-4c62-bbae-27ad637c13d9', 'molduras.whatsapp', '{"pt":"Olá, queria um orçamento de moldura.","en":"Hello, I would like a quote for framing.","es":"Hola, quería un presupuesto de marco."}', 'Mensagem já escrita quando o visitante abre o WhatsApp daqui.', 'molduras', 1790241005);
--> statement-breakpoint
INSERT OR IGNORE INTO textos (id, chave, valor, nota, grupo, actualizado_em) VALUES ('a59d9a6a-c436-407e-b2dd-4274c32dcf5e', 'molduras.passo1.titulo', '{"pt":"01 · MEDIR","en":"01 · MEASURE","es":"01 · MEDIR"}', 'Passo 1 do processo. O número vem à frente no desenho.', 'molduras', 1790241005);
--> statement-breakpoint
INSERT OR IGNORE INTO textos (id, chave, valor, nota, grupo, actualizado_em) VALUES ('2ef00596-21e5-461e-9075-95a103156818', 'molduras.passo1.texto', '{"pt":"Diz-nos as medidas da obra, ou levantamo-la em sua casa.","en":"Tell us the dimensions, or we collect the work from you.","es":"Díganos las medidas, o recogemos la obra en su casa."}', 'O que acontece no passo 1.', 'molduras', 1790241005);
--> statement-breakpoint
INSERT OR IGNORE INTO textos (id, chave, valor, nota, grupo, actualizado_em) VALUES ('58b9be03-8863-438f-a054-315b5e7c51f7', 'molduras.passo2.titulo', '{"pt":"02 · ESCOLHER","en":"02 · CHOOSE","es":"02 · ELEGIR"}', 'Passo 2 do processo. O número vem à frente no desenho.', 'molduras', 1790241005);
--> statement-breakpoint
INSERT OR IGNORE INTO textos (id, chave, valor, nota, grupo, actualizado_em) VALUES ('1571e60c-6478-4c16-9b6e-aa179db1ac4b', 'molduras.passo2.texto', '{"pt":"Vê madeiras, alumínios e vidros, com orçamento na hora.","en":"See woods, aluminium and glass, with a quote on the spot.","es":"Vea maderas, aluminios y vidrios, con presupuesto al momento."}', 'O que acontece no passo 2.', 'molduras', 1790241005);
--> statement-breakpoint
INSERT OR IGNORE INTO textos (id, chave, valor, nota, grupo, actualizado_em) VALUES ('4ad5411b-0dcd-474a-8dff-d385379c25d9', 'molduras.passo3.titulo', '{"pt":"03 · PRODUZIR","en":"03 · MAKE","es":"03 · PRODUCIR"}', 'Passo 3 do processo. O número vem à frente no desenho.', 'molduras', 1790241005);
--> statement-breakpoint
INSERT OR IGNORE INTO textos (id, chave, valor, nota, grupo, actualizado_em) VALUES ('89240bef-dc3d-450a-9511-29c90297efd4', 'molduras.passo3.texto', '{"pt":"A MOLDARTPÓVOA produz a moldura à medida na fábrica.","en":"MOLDARTPÓVOA makes the frame to measure at the factory.","es":"MOLDARTPÓVOA produce el marco a medida en fábrica."}', 'O que acontece no passo 3.', 'molduras', 1790241005);
--> statement-breakpoint
INSERT OR IGNORE INTO textos (id, chave, valor, nota, grupo, actualizado_em) VALUES ('22aaf8c0-4d1b-463f-8961-a615e5ee9d78', 'molduras.passo4.titulo', '{"pt":"04 · INSTALAR","en":"04 · INSTALL","es":"04 · INSTALAR"}', 'Passo 4 do processo. O número vem à frente no desenho.', 'molduras', 1790241005);
--> statement-breakpoint
INSERT OR IGNORE INTO textos (id, chave, valor, nota, grupo, actualizado_em) VALUES ('a67f2f88-de2d-4bf6-840f-94a2ec7f43d5', 'molduras.passo4.texto', '{"pt":"Entregamos e deixamos a obra pendurada no sítio certo.","en":"We deliver and hang the work in the right place.","es":"Entregamos y dejamos la obra colgada en el sitio adecuado."}', 'O que acontece no passo 4.', 'molduras', 1790241005);
