INSERT OR IGNORE INTO textos (id, chave, valor, nota, grupo, actualizado_em) VALUES ('30ad22b1-a478-4dd7-8028-c3aa07699d97', 'contactos.descricao', '{"pt":"Fale com a Galeria Contagiarte por WhatsApp, email ou telefone.","en":"Reach Galeria Contagiarte on WhatsApp, by email or by phone.","es":"Contacte con la Galería Contagiarte por WhatsApp, email o teléfono."}', 'Descrição da página nos motores de busca e nos cartões de partilha.', 'contactos', 1790244774);
--> statement-breakpoint
INSERT OR IGNORE INTO textos (id, chave, valor, nota, grupo, actualizado_em) VALUES ('72ccd1fc-b008-47de-a8e9-a189e61e92a5', 'contactos.intro', '{"pt":"O WhatsApp é o caminho mais rápido. Respondemos todos os dias.","en":"WhatsApp is the fastest route. We answer every day.","es":"WhatsApp es la vía más rápida. Respondemos todos los días."}', 'Frase de abertura, ao lado dos contactos.', 'contactos', 1790244774);
--> statement-breakpoint
INSERT OR IGNORE INTO textos (id, chave, valor, nota, grupo, actualizado_em) VALUES ('c4710d61-1513-41e0-9787-1e5d5998d72d', 'contactos.whatsapp.visita', '{"pt":"Olá, queria marcar uma visita à galeria.","en":"Hello, I would like to book a visit to the gallery.","es":"Hola, quería concertar una visita a la galería."}', 'Mensagem já escrita no botão de marcar visita.', 'contactos', 1790244774);
--> statement-breakpoint
INSERT OR IGNORE INTO textos (id, chave, valor, nota, grupo, actualizado_em) VALUES ('fc528322-b0ab-459e-9f68-f73cfd499af7', 'whatsapp.site', '{"pt":"Olá, venho do site da Galeria Contagiarte.","en":"Hello, I came from the Galeria Contagiarte website.","es":"Hola, vengo del sitio de la Galería Contagiarte."}', 'Mensagem já escrita nos botões de WhatsApp que não são de um assunto em particular: o botão flutuante, o rodapé e a página de contactos.', 'geral', 1790244774);
--> statement-breakpoint
INSERT OR IGNORE INTO textos (id, chave, valor, nota, grupo, actualizado_em) VALUES ('cc79a864-f901-425a-9f85-f2de4ea33878', 'newsletter.etiqueta', '{"pt":"NEWSLETTER","en":null,"es":null}', 'Etiqueta por cima do bloco de subscrição, na entrada e nos contactos.', 'newsletter', 1790244774);
