INSERT OR IGNORE INTO textos (id, chave, valor, nota, grupo, actualizado_em) VALUES ('84ab26d8-ef33-4093-bded-da3b1937e1ca', 'home.destaque.alt', '{"pt":"{obra}, exposição em curso","en":"{obra}, exhibition on show","es":"{obra}, exposición en curso"}', 'Alternativa da fotografia do herói quando há exposição em curso. Aceita {obra} como marcador, que é substituído pelo título da exposição.', 'homepage', 1790245280);
--> statement-breakpoint
INSERT OR IGNORE INTO textos (id, chave, valor, nota, grupo, actualizado_em) VALUES ('907ddff8-3d32-4ca9-8ba7-47edee555430', 'home.destaque.alt.sem', '{"pt":"Obra em destaque da Galeria Contagiarte","en":"Featured work at Galeria Contagiarte","es":"Obra destacada de la Galería Contagiarte"}', 'Alternativa da fotografia do herói quando não há exposição em curso.', 'homepage', 1790245280);
--> statement-breakpoint
INSERT OR IGNORE INTO textos (id, chave, valor, nota, grupo, actualizado_em) VALUES ('85e9693d-68b1-40aa-b0e3-2945aa261c37', 'home.destaque.legenda', '{"pt":"Obra em destaque","en":"Featured work","es":"Obra destacada"}', 'Texto do marcador do herói enquanto não houver fotografia carregada.', 'homepage', 1790245280);
--> statement-breakpoint
INSERT OR IGNORE INTO textos (id, chave, valor, nota, grupo, actualizado_em) VALUES ('fc270076-40c0-4b0a-91a8-abfaba0e98bf', 'home.galeria.imagem.alt', '{"pt":"Rui Pedro e Maria João, art dealers da Galeria Contagiarte","en":"Rui Pedro and Maria João, art dealers at Galeria Contagiarte","es":"Rui Pedro y Maria João, art dealers de la Galería Contagiarte"}', 'Alternativa do retrato na secção A galeria.', 'homepage', 1790245280);
--> statement-breakpoint
INSERT OR IGNORE INTO textos (id, chave, valor, nota, grupo, actualizado_em) VALUES ('4843e281-89c4-4b04-89a5-652acde9f045', 'home.galeria.imagem.legenda', '{"pt":"Rui Pedro & Maria João, art dealers","en":null,"es":null}', 'Texto do marcador da secção A galeria enquanto não houver retrato.', 'homepage', 1790245280);
