INSERT OR IGNORE INTO textos (id, chave, valor, nota, grupo, actualizado_em) VALUES ('62525147-3a1b-4e77-91dc-178f3d27107f', 'descarregar.descricao', '{"pt":"Catálogo, dossiers de exposição e flyers da Galeria Contagiarte, em PDF.","en":"Catalogue, exhibition press kits and flyers from Galeria Contagiarte, in PDF.","es":"Catálogo, dosieres de exposición y folletos de la Galería Contagiarte, en PDF."}', 'Descrição da página nos motores de busca.', 'descarregáveis', 1790258103);
--> statement-breakpoint
INSERT OR IGNORE INTO textos (id, chave, valor, nota, grupo, actualizado_em) VALUES ('167a952e-a414-4486-93b8-02c9543855c3', 'privacidade.descricao', '{"pt":"Que dados a galeria guarda quando alguém envia um pedido ou subscreve a newsletter, durante quanto tempo, e como se pedem apagados.","en":"What the gallery stores when someone sends an enquiry or subscribes, for how long, and how to ask for it to be deleted.","es":"Qué datos guarda la galería cuando alguien envía una solicitud o se suscribe, durante cuánto tiempo, y cómo pedir que se borren."}', 'Descrição da página nos motores de busca.', 'legal', 1790258103);
--> statement-breakpoint
INSERT OR IGNORE INTO textos (id, chave, valor, nota, grupo, actualizado_em) VALUES ('17cac5cb-0b88-4957-8e6c-03c6ac1e8eb4', 'arquivo.descricao', '{"pt":"Arquivo de exposições e curadorias da Galeria Contagiarte, ano a ano.","en":"Archive of exhibitions and curatorial projects by Galeria Contagiarte, year by year.","es":"Archivo de exposiciones y curadurías de la Galería Contagiarte, año a año."}', 'Descrição da página nos motores de busca.', 'arquivo', 1790258103);
--> statement-breakpoint
INSERT OR IGNORE INTO textos (id, chave, valor, nota, grupo, actualizado_em) VALUES ('3d438713-aca1-40e1-a664-75b2774f32b0', 'artistas.descricao', '{"pt":"Os artistas representados pela Galeria Contagiarte, entre pintura, escultura, cerâmica e colagem.","en":"The artists represented by Galeria Contagiarte, across painting, sculpture, ceramics and collage.","es":"Los artistas representados por la Galería Contagiarte, entre pintura, escultura, cerámica y collage."}', 'Descrição da página nos motores de busca.', 'artistas', 1790258103);
--> statement-breakpoint
INSERT OR IGNORE INTO textos (id, chave, valor, nota, grupo, actualizado_em) VALUES ('7ffb2393-41f7-4ccc-b620-467d0a9cf4f1', 'exposicoes.descricao', '{"pt":"Exposições e curadorias da Galeria Contagiarte, em adegas, hotéis, clubes e centros culturais.","en":"Exhibitions and curatorial projects by Galeria Contagiarte, in wineries, hotels, clubs and cultural centres.","es":"Exposiciones y curadurías de la Galería Contagiarte, en bodegas, hoteles, clubes y centros culturales."}', 'Descrição da página nos motores de busca.', 'exposições', 1790258103);
--> statement-breakpoint
INSERT OR IGNORE INTO textos (id, chave, valor, nota, grupo, actualizado_em) VALUES ('246fe0b9-8df5-4032-954c-c0db91799a85', 'obras.descricao', '{"pt":"Obras disponíveis na Galeria Contagiarte: pintura, escultura, cerâmica e técnica mista de artistas nacionais e internacionais.","en":"Works available at Galeria Contagiarte: painting, sculpture, ceramics and mixed media by Portuguese and international artists.","es":"Obras disponibles en la Galería Contagiarte: pintura, escultura, cerámica y técnica mixta de artistas nacionales e internacionales."}', 'Descrição da página nos motores de busca.', 'obras', 1790258103);
--> statement-breakpoint
INSERT OR IGNORE INTO textos (id, chave, valor, nota, grupo, actualizado_em) VALUES ('d72407e2-4047-4366-83e5-0a6869e606d8', 'lugares.descricao', '{"pt":"Adegas, hotéis, clubes e centros culturais onde a Galeria Contagiarte expõe.","en":"Wineries, hotels, clubs and cultural centres where Galeria Contagiarte exhibits.","es":"Bodegas, hoteles, clubes y centros culturales donde expone la Galería Contagiarte."}', 'Descrição da página nos motores de busca.', 'lugares', 1790258103);
--> statement-breakpoint
INSERT OR IGNORE INTO textos (id, chave, valor, nota, grupo, actualizado_em) VALUES ('b1f4853a-5e52-4154-bdf9-6ed39fab4f31', 'ativo.descricao', '{"pt":"O que faz uma obra de arte valorizar, o que a galeria avalia antes de representar um artista, e o que ninguém honesto lhe pode prometer.","en":"What makes a work of art appreciate, what the gallery assesses before representing an artist, and what nobody honest can promise you.","es":"Qué hace que una obra de arte se revalorice, qué evalúa la galería antes de representar a un artista, y lo que nadie honesto puede prometerle."}', 'Descrição da página nos motores de busca.', 'ativo', 1790258103);
--> statement-breakpoint
INSERT OR IGNORE INTO textos (id, chave, valor, nota, grupo, actualizado_em) VALUES ('11a9539f-0e94-4f2b-8402-416b00e0e970', 'descarregar.vazio', '{"pt":"Ainda não há documentos publicados. Assim que o catálogo estiver carregado, aparece aqui.","en":"No documents published yet. As soon as the catalogue is uploaded, it appears here.","es":"Todavía no hay documentos publicados. En cuanto el catálogo esté cargado, aparecerá aquí."}', 'O que o visitante lê enquanto não houver documentos publicados.', 'descarregáveis', 1790258103);
--> statement-breakpoint
INSERT OR IGNORE INTO textos (id, chave, valor, nota, grupo, actualizado_em) VALUES ('fae7545a-c8c0-4af5-bb67-de1db6679f27', 'privacidade.nota', '{"pt":"Rascunho por rever juridicamente. Última atualização: por definir.","en":"Draft pending legal review. Last updated: to be defined.","es":"Borrador pendiente de revisión jurídica. Última actualización: por definir."}', 'Aviso por cima do texto legal. Tirar quando um advogado o rever.', 'legal', 1790258103);
--> statement-breakpoint
INSERT OR IGNORE INTO textos (id, chave, valor, nota, grupo, actualizado_em) VALUES ('d8a173cc-f7a7-4fb0-a55d-ae152f94d24f', 'ativo.whatsapp', '{"pt":"Olá, queria perceber melhor o percurso dos artistas que representam.","en":"Hello, I would like to understand the careers of the artists you represent.","es":"Hola, quería entender mejor la trayectoria de los artistas que representan."}', 'Mensagem já escrita no botão de WhatsApp desta página.', 'ativo', 1790258103);
--> statement-breakpoint
INSERT OR IGNORE INTO textos (id, chave, valor, nota, grupo, actualizado_em) VALUES ('c348cb72-ca58-406a-b3ee-820fd80c3920', '404.whatsapp', '{"pt":"Olá, andava à procura de algo no site.","en":"Hello, I was looking for something on the website.","es":"Hola, estaba buscando algo en el sitio."}', 'Mensagem já escrita no botão de WhatsApp da página de erro.', '404', 1790258213);
